server:
    port: 10080
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: pzyf@2018
        url: jdbc:mysql://test.carfunny.com.cn:3306/flaky?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&allowMultiQueries=true
        username: pzyf
    resources:
        static-locations: file:///D:/Temp/resources/static/,file:///D:/Temp/resources/resource/templates/
string:
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: LEGACYHTML5
        servlet:
            content-type: text/html
